name: Changeset Bot

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  changeset-bot:
    runs-on: ubuntu-latest
    name: Changeset Bot

    steps:
      - uses: actions/checkout@v3

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
